name: build installer

run-name: installer-build-${{ github.sha }}

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          python-version: "3.11"
          activate-environment: 'cp311_libuv'

      - name: Install libuv dependency
        run: |
          conda install -y libuv
          conda env list
          conda env list | findstr libuv
          ls C:\Users\runneradmin\miniconda3\envs\cp311_libuv
          echo "$(conda env list | findstr libuv)"
          echo "$($(conda env list | findstr libuv) -split ' ' | Select-Object -Last 1)" 
          echo "LIBUV_PATH=$($(conda env list | findstr libuv) -split ' ' | Select-Object -Last 1)"
          echo "LIBUV_PATH=$($(conda env list | findstr libuv) -split ' ' | Select-Object -Last 1)" >> $env:GITHUB_ENV

      - name: test
        run: |
          echo "${{ env.LIBUV_PATH }}"
          echo "${{ env.LIBUV_PATH }}\Library"
          dir "${{ env.LIBUV_PATH }}"
          dir "${{ env.LIBUV_PATH }}\Library" -recurse -depth 2
